In [2]:
import pandas
with open("nba_2013.csv", 'r') as csvfile:
    nba = pandas.read_csv(csvfile)

# The names of all the columns in the data.
print(nba.columns.values)

['player' 'pos' 'age' 'bref_team_id' 'g' 'gs' 'mp' 'fg' 'fga' 'fg.' 'x3p'
 'x3pa' 'x3p.' 'x2p' 'x2pa' 'x2p.' 'efg.' 'ft' 'fta' 'ft.' 'orb' 'drb'
 'trb' 'ast' 'stl' 'blk' 'tov' 'pf' 'pts' 'season' 'season_end']

In [3]:
selected_player = nba[nba["player"] == "LeBron James"].iloc[0]

In [4]:
distance_columns = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts']

In [5]:
nba.shape

(481, 31)

In [6]:
nba=nba.dropna()

In [7]:
nba.shape

(403, 31)

In [8]:
import math
import matplotlib.pyplot as plt

player = nba[nba["player"] == "Kevin Durant"].iloc[0]

# Use Numeric Columns Only
measure = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts']

# find the distance
def ed(row):
    value = 0
    for k in measure:
        value += (row[k] - player[k]) ** 2
    return math.sqrt(value)

# return result
durant = nba.apply(ed, axis=1)

In [9]:
player = nba[nba["player"] == "Carmelo Anthony"].iloc[0]

# Use Numeric Columns Only
measure = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts']

# find the distance
def ed(row):
    value = 0
    for k in measure:
        value += (row[k] - player[k]) ** 2
    return math.sqrt(value)

# return result
anthony = nba.apply(ed, axis=1)

In [10]:
player = nba[nba["player"] == "LeBron James"].iloc[0]

# Use Numeric Columns Only
measure = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts']

# find the distance
def ed(row):
    value = 0
    for k in measure:
        value += (row[k] - player[k]) ** 2
    return math.sqrt(value)

# return result
james = nba.apply(ed, axis=1)

In [12]:
# Select only the numeric columns from the NBA dataset
nba_numeric = nba[measure]

# Normalize all of the numeric columns
nba_normalized = (nba_numeric - nba_numeric.mean()) / nba_numeric.std()

In [13]:
nba_normalized.head(8)

,age,g,gs,mp,fg,fga,fg.,x3p,x3pa,x3p.,...,ft.,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,-0.814777,0.235407,-0.944580,-0.613829,-0.877328,-0.925592,0.482473,-0.826813,-0.859228,-0.115785,...,-0.589593,0.233644,-0.225131,-0.090114,-0.763546,-0.624501,0.044941,-0.803874,0.102809,-0.874569
3,0.352916,0.676249,1.455748,1.338616,1.426921,1.432458,0.359705,1.545983,1.248019,0.935220,...,0.519979,-0.412605,0.375022,0.142778,0.864779,-0.279742,-0.705609,1.028200,0.306263,1.568399
4,-0.347700,-0.073182,0.041856,-0.494735,-0.472058,-0.632869,1.546458,-0.903355,-0.962741,-1.867461,...,0.670309,0.589081,0.047031,0.218722,-0.674728,-0.624501,0.697593,-0.282680,1.047417,-0.543641
6,0.352916,0.499912,1.324224,1.276779,2.515361,2.549144,0.346064,-0.845948,-0.859228,-0.553704,...,0.570089,1.752328,2.950097,2.689410,0.346676,0.524695,1.415510,0.664944,0.466120,2.143835
7,-0.581239,0.323576,-0.878818,-0.356175,-0.483638,-0.494638,0.196015,-0.865084,-0.874015,-0.856879,...,-0.589593,0.992986,0.109838,0.390860,-0.445282,-0.595771,0.273369,-0.582761,0.160939,-0.596336
8,2.688302,0.676249,-0.648649,0.633217,0.130057,0.163989,0.127811,1.316357,1.314564,0.598490,...,1.164247,-0.558011,0.040053,-0.145806,0.087624,0.266126,-0.542446,0.048988,0.001082,0.242578
9,1.287070,-0.117266,-0.023906,-0.120278,-0.078368,-0.188363,0.837134,-0.692865,-0.622624,-0.330086,...,-0.818666,0.346737,-0.329809,-0.130617,-0.275048,1.300403,-0.183488,0.143750,0.088276,-0.191634
10,-0.814777,0.984838,1.192699,0.758036,0.095320,0.031180,0.564318,-0.654594,-0.615231,-0.088415,...,-0.560959,1.154548,1.331080,1.327494,-0.127019,1.070563,0.436532,0.112163,0.466120,-0.029332

In [14]:
from scipy.spatial import distance

# Find the normalized vector for lebron james.
durant_normalized = nba_normalized[nba["player"] == "Kevin Durant"]

# Find the distance between lebron james and everyone else.
euclidean_distances = nba_normalized.apply(lambda row: distance.euclidean(row, durant_normalized), axis=1)

# Create a new dataframe with distances.
distance_frame = pandas.DataFrame(data={"dist": euclidean_distances, "idx": euclidean_distances.index})
distance_frame.sort_values(by="dist", inplace=True)
# Find the most similar player to lebron (the lowest distance to lebron is lebron, the second smallest is the most similar non-lebron player)
second_smallest = distance_frame.iloc[1]["idx"]
most_similar = nba.loc[int(second_smallest)]["player"]
most_similar

'Carmelo Anthony'

In [15]:
import random
from numpy.random import permutation

# Randomly shuffle the index of nba.
random_indices = permutation(nba.index)
# Set a cutoff for how many items we want in the test set (in this case 1/3 of the items)
test_cutoff = math.floor(len(nba)/3)
# Generate the test set by taking the first 1/3 of the randomly shuffled indices.
test = nba.loc[random_indices[1:test_cutoff]]
# Generate the train set with the rest of the data.
train = nba.loc[random_indices[test_cutoff:]]
# The columns that we will be making predictions with.
x_columns = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf']
# The column that we want to predict.
y_column = ["pts"]

from sklearn.neighbors import KNeighborsRegressor
# Create the knn model.
# Look at the five closest neighbors.
knn = KNeighborsRegressor(n_neighbors=7)
# Fit the model on the training data.
knn.fit(train[x_columns], train[y_column])
# Make point predictions on the test set using the fit model.
predictions = knn.predict(test[x_columns])
# Get the actual values for the test set.
actual = test[y_column]

# Compute the mean squared error of our predictions.
mse = (((predictions - actual) ** 2).sum()) / len(predictions)
print("actual[:20]:\n", actual[:20])
print("mse:", mse)

actual[:20]:
       pts
47     72
182    26
171  1068
201   871
313   796
154   910
426   461
129  1095
287    74
33    625
43    911
57    491
87    716
410    18
111   529
10    572
294   201
108    26
34    166
475   343
mse: pts    4703.938315
dtype: float64